run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor/
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
    - path: internal/
      text: "should have comment"
      linters:
        - revive
    - linters:
        - gosec
      text: "G404: Use of weak random number generator"
      path: pkg/.*\.go

linters:
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - goimports
    - prealloc
    - bodyclose
    - contextcheck
    - depguard
    - dogsled
    - dupl
    - gocritic
    - gocognit
    - goconst
    - godot
    - err113
    - goheader
    - mnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - lll
    - makezero
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - promlinter
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varnamelen
    - whitespace
    - wrapcheck
  disable:
    - wsl

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 3
  mnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
  lll:
    line-length: 140
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - wrapperFunc
      - httpNoBody
  gosec:
    excludes:
      - G404 # Use of weak random number generator
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
  varnamelen:
    ignoreNames:
      - rw
      - w
      - r
      - id
      - db
      - tx
      - err
      - ok
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/nx211/traefik-webfinger
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16"
      tests:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/nx211/traefik-webfinger
          - github.com/stretchr/testify
  wsl:
    allow-cuddle-declarations: true
    allow-trailing-comment: true
    force-case-trailing-whitespace: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
